### ISSUE TITLE
Antifall could use of a toggle or being more configurable

### ISSUE THREAD

**Issue by dimaguy** [Ale32bit-CC/Minit#2]
As a user of minit, I can't help but notice that antifall triggers a lot when it's not needed, I'm a fanatic of feather falling IV enchantments so it could have more spacing between triggers

**Comment by Ale32bit** [comment]
Added with 2ae858ab70a78871267a029be5892683707383c9 and e97ef3e471cd58e0411a6fad404bf95b64c58139
